export const allSuggestions = [
    "Agatha Christie",
    "Aldous Huxley",
    "Alexandre Dumas",
    "Amitav Ghosh",
    "Anita Desai",
    "Antoine de Saint-Exupéry",
    "Aravind Adiga",
    "Arundhati Roy",
    "Arthur Conan Doyle",
    "Bram Stoker",
    "Carlos Ruiz Zafón",
    "Charles Dickens",
    "Charlotte Brontë",
    "Charlotte Perkins Gilman",
    "Chetan Bhagat",
    "Chimamanda Ngozi Adichie",
    "Chinua Achebe",
    "Colson Whitehead",
    "Daphne du Maurier",
    "Donna Tartt",
    "Douglas Adams",
    "Emily Brontë",
    "Ernest Hemingway",
    "F. Scott Fitzgerald",
    "Frank Herbert",
    "Fyodor Dostoevsky",
    "Gabriel Garcia Marquez",
    "Gail Honeyman",
    "George Bernard Shaw",
    "George Orwell",
    "Geraldine Brooks",
    "Gustave Flaubert",
    "Han Kang",
    "Harper Lee",
    "Harriet Beecher Stowe",
    "Haruki Murakami",
    "Henryk Sienkiewicz",
    "Herman Hesse",
    "Herman Melville",
    "Homer",
    "Italo Calvino",
    "J.D. Salinger",
    "J.K. Rowling",
    "J.R.R. Tolkien",
    "Jack London",
    "James Joyce",
    "Jane Austen",
    "Jean Rhys",
    "Jhumpa Lahiri",
    "John Steinbeck",
    "José Saramago",
    "Joseph Conrad",
    "Joseph Heller",
    "Jules Verne",
    "Kazuo Ishiguro",
    "Khaled Hosseini",
    "Khushwant Singh",
    "Kiran Desai",
    "Leo Tolstoy",
    "Louisa May Alcott",
    "Marcus Aurelius",
    "Margaret Atwood",
    "Markus Zusak",
    "Mary Shelley",
    "Maya Angelou",
    "Michael Chabon",
    "Michael Ondaatje",
    "Milan Kundera",
    "Miguel de Cervantes",
    "Nikos Kazantzakis",
    "Oscar Wilde",
    "Orson Scott Card",
    "Patrick Süskind",
    "Paulo Coelho",
    "Piers Anthony",
    "Plato",
    "Premchand",
    "R.K. Narayan",
    "Rabindranath Tagore",
    "Ralph Ellison",
    "Ramdhari Singh 'Dinkar'",
    "Ray Bradbury",
    "Robert M. Pirsig",
    "Rudyard Kipling",
    "Salman Rushdie",
    "Sun Tzu",
    "Susan Cain",
    "Thomas Hardy",
    "Tim O'Brien",
    "Toni Morrison",
    "V.S. Naipaul",
    "Valmiki",
    "Victor Hugo",
    "Vikram Chandra",
    "Vikram Seth",
    "Virginia Woolf",
    "Vyasa",
    "Walter Tevis",
    "William Shakespeare",
    "William Makepeace Thackeray",
    "Yann Martel",
    "Yuval Noah Harari",
    "Zadie Smith",
  ];